[package]
name = "elixir_parser"
version = "0.1.0"
authors = ["Gabe Durazo <gabe@durazo.us>"]

[build-dependencies]
lalrpop = "0.16.2"

[dependencies]
num-bigint = "0.2.2"
num-traits = "0.2.2"
itertools = "0.8"
lalrpop-util = "0.16.2"
regex = "0.2.0"